
// [AUTOGENERATED]


using System;
using Asset;

namespace SB09WiiEvent{
    public static class SB09WiiEventCaster{
        public static Asset.EventEntity Cast(Asset.Event eventType, object file = null){

            Type targetType = eventType switch
            {
                Event.SetPlayerPosition => typeof(SetPlayerPosition),
                _ => null
            };

            if (targetType == null) return null;

            // Neat way of allowing either empty construction or file construction
            return file == null
                    ? (EventEntity)Activator.CreateInstance(targetType)!             // no-arg constructor
                    : (EventEntity)Activator.CreateInstance(targetType, (HoArchive.MemoryStreamEndian)file)!;       // single-arg constructor

        }
    }
}