
// [AUTOGENERATED]

namespace SB09WiiAsset{
    public static class SB09WiiAssetCaster{
        public static Asset.AssetEntity ReadAsset(HoArchive.MemoryStreamEndian file, HoArchive.wmlTypeID wmlTypeID){
            if (wmlTypeID < HoArchive.wmlTypeID.FXObjectSystem){
                if (wmlTypeID < HoArchive.wmlTypeID.Hammer){
                    if (wmlTypeID < HoArchive.wmlTypeID.HitButton){
                        if (wmlTypeID < HoArchive.wmlTypeID.GenericSpawner){
                            if (wmlTypeID < HoArchive.wmlTypeID.CharacterAssets){
                                if (wmlTypeID < HoArchive.wmlTypeID.Direction){
                                    if (wmlTypeID < HoArchive.wmlTypeID.Fog){
                                        if (wmlTypeID < HoArchive.wmlTypeID.Env){
                                            return new BSP(file);
                                        }
                                        return new Env(file);
                                    }
                                    return new Fog(file);
                                }
                                if (wmlTypeID < HoArchive.wmlTypeID.Font){
                                    return new Direction(file);
                                }
                                return new Font(file);
                            }
                            if (wmlTypeID < HoArchive.wmlTypeID.TextureAnimationSettings){
                                if (wmlTypeID < HoArchive.wmlTypeID.GenericShader){
                                    return new CharacterAssets(file);
                                }
                                return new GenericShader(file);
                            }
                            if (wmlTypeID < HoArchive.wmlTypeID.Tiki){
                                return new TextureAnimationSettings(file);
                            }
                            return new Tiki(file);
                        }
                        if (wmlTypeID < HoArchive.wmlTypeID.Reference){
                            if (wmlTypeID < HoArchive.wmlTypeID.ShaderCodeBlob){
                                if (wmlTypeID < HoArchive.wmlTypeID.Portal){
                                    return new GenericSpawner(file);
                                }
                                return new Portal(file);
                            }
                            if (wmlTypeID < HoArchive.wmlTypeID.ElectricPoint){
                                return new ShaderCodeBlob(file);
                            }
                            return new ElectricPoint(file);
                        }
                        if (wmlTypeID < HoArchive.wmlTypeID.Material){
                            if (wmlTypeID < HoArchive.wmlTypeID.SoundFX){
                                return new Reference(file);
                            }
                            return new SoundFX(file);
                        }
                        if (wmlTypeID < HoArchive.wmlTypeID.RawAsset){
                            return new Material(file);
                        }
                        return new RawAsset(file);
                    }
                    if (wmlTypeID < HoArchive.wmlTypeID.Checkpoint){
                        if (wmlTypeID < HoArchive.wmlTypeID.FXScreenWarp){
                            if (wmlTypeID < HoArchive.wmlTypeID.SoundFXMultiple){
                                if (wmlTypeID < HoArchive.wmlTypeID.BuyScreen){
                                    return new HitButton(file);
                                }
                                return new BuyScreen(file);
                            }
                            if (wmlTypeID < HoArchive.wmlTypeID.ScaleformAsset){
                                return new SoundFXMultiple(file);
                            }
                            return new ScaleformAsset(file);
                        }
                        if (wmlTypeID < HoArchive.wmlTypeID.Texture){
                            if (wmlTypeID < HoArchive.wmlTypeID.NPCTemplate){
                                return new FXScreenWarp(file);
                            }
                            return new NPCTemplate(file);
                        }
                        if (wmlTypeID < HoArchive.wmlTypeID.CylinderAsset){
                            return new Texture(file);
                        }
                        return new CylinderAsset(file);
                    }
                    if (wmlTypeID < HoArchive.wmlTypeID.Light_Effect_Flicker){
                        if (wmlTypeID < HoArchive.wmlTypeID.UVMovementSettings){
                            if (wmlTypeID < HoArchive.wmlTypeID.Script){
                                return new Checkpoint(file);
                            }
                            return new Script(file);
                        }
                        if (wmlTypeID < HoArchive.wmlTypeID.ImmediateGeometry){
                            return new UVMovementSettings(file);
                        }
                        return new ImmediateGeometry(file);
                    }
                    if (wmlTypeID < HoArchive.wmlTypeID.Spinner){
                        if (wmlTypeID < HoArchive.wmlTypeID.ShrapnelAssetDef){
                            return new Light_Effect_Flicker(file);
                        }
                        return new ShrapnelAssetDef(file);
                    }
                    if (wmlTypeID < HoArchive.wmlTypeID.TriggerEnt){
                        return new Spinner(file);
                    }
                    return new TriggerEnt(file);
                }
                if (wmlTypeID < HoArchive.wmlTypeID.AnimationSet){
                    if (wmlTypeID < HoArchive.wmlTypeID.SoundsNamed){
                        if (wmlTypeID < HoArchive.wmlTypeID.Fountain){
                            if (wmlTypeID < HoArchive.wmlTypeID.Dispatcher){
                                if (wmlTypeID < HoArchive.wmlTypeID.Light){
                                    return new Hammer(file);
                                }
                                return new Light(file);
                            }
                            if (wmlTypeID < HoArchive.wmlTypeID.Trampoline){
                                return new Dispatcher(file);
                            }
                            return new Trampoline(file);
                        }
                        if (wmlTypeID < HoArchive.wmlTypeID.Model){
                            if (wmlTypeID < HoArchive.wmlTypeID.VertexDecl){
                                return new Fountain(file);
                            }
                            return new VertexDecl(file);
                        }
                        if (wmlTypeID < HoArchive.wmlTypeID.Camera){
                            return new Model(file);
                        }
                        return new Camera(file);
                    }
                    if (wmlTypeID < HoArchive.wmlTypeID.SurfaceGamePlay){
                        if (wmlTypeID < HoArchive.wmlTypeID.ScreenFade){
                            if (wmlTypeID < HoArchive.wmlTypeID.TikiScreen){
                                return new SoundsNamed(file);
                            }
                            return new TikiScreen(file);
                        }
                        if (wmlTypeID < HoArchive.wmlTypeID.SoundCue){
                            return new ScreenFade(file);
                        }
                        return new SoundCue(file);
                    }
                    if (wmlTypeID < HoArchive.wmlTypeID.BreakawayPlatform){
                        if (wmlTypeID < HoArchive.wmlTypeID.ScreenWarp){
                            return new SurfaceGamePlay(file);
                        }
                        return new ScreenWarp(file);
                    }
                    if (wmlTypeID < HoArchive.wmlTypeID.Transition_Time){
                        return new BreakawayPlatform(file);
                    }
                    return new Transition_Time(file);
                }
                if (wmlTypeID < HoArchive.wmlTypeID.Player_Location_Ent_Connector){
                    if (wmlTypeID < HoArchive.wmlTypeID.SkinGeometry){
                        if (wmlTypeID < HoArchive.wmlTypeID.InflatablePlatform){
                            if (wmlTypeID < HoArchive.wmlTypeID.UIDReference){
                                return new AnimationSet(file);
                            }
                            return new UIDReference(file);
                        }
                        if (wmlTypeID < HoArchive.wmlTypeID.LoadingScreen){
                            return new InflatablePlatform(file);
                        }
                        return new LoadingScreen(file);
                    }
                    if (wmlTypeID < HoArchive.wmlTypeID.MovePoint){
                        if (wmlTypeID < HoArchive.wmlTypeID.Camera_Tweak){
                            return new SkinGeometry(file);
                        }
                        return new Camera_Tweak(file);
                    }
                    if (wmlTypeID < HoArchive.wmlTypeID.AnimList){
                        return new MovePoint(file);
                    }
                    return new AnimList(file);
                }
                if (wmlTypeID < HoArchive.wmlTypeID.RenderMode){
                    if (wmlTypeID < HoArchive.wmlTypeID.SoundWiimoteSpeakerList){
                        if (wmlTypeID < HoArchive.wmlTypeID.CurveCamera){
                            return new Player_Location_Ent_Connector(file);
                        }
                        return new CurveCamera(file);
                    }
                    if (wmlTypeID < HoArchive.wmlTypeID.Rumble){
                        return new SoundWiimoteSpeakerList(file);
                    }
                    return new Rumble(file);
                }
                if (wmlTypeID < HoArchive.wmlTypeID.CameraD){
                    if (wmlTypeID < HoArchive.wmlTypeID.HintSphere){
                        return new RenderMode(file);
                    }
                    return new HintSphere(file);
                }
                if (wmlTypeID < HoArchive.wmlTypeID.UI_Flash_On_Screen_Text){
                    return new CameraD(file);
                }
                return new UI_Flash_On_Screen_Text(file);
            }
            if (wmlTypeID < HoArchive.wmlTypeID.CollisionMesh){
                if (wmlTypeID < HoArchive.wmlTypeID.FXSpawn){
                    if (wmlTypeID < HoArchive.wmlTypeID.ProjectileAsset){
                        if (wmlTypeID < HoArchive.wmlTypeID.BehaviorTree){
                            if (wmlTypeID < HoArchive.wmlTypeID.FXParticleSystem){
                                if (wmlTypeID < HoArchive.wmlTypeID.ScaleformPlayer){
                                    return new FXObjectSystem(file);
                                }
                                return new ScaleformPlayer(file);
                            }
                            if (wmlTypeID < HoArchive.wmlTypeID.ElectricArc){
                                return new FXParticleSystem(file);
                            }
                            return new ElectricArc(file);
                        }
                        if (wmlTypeID < HoArchive.wmlTypeID.StaticGeometry){
                            if (wmlTypeID < HoArchive.wmlTypeID.WallNet){
                                return new BehaviorTree(file);
                            }
                            return new WallNet(file);
                        }
                        if (wmlTypeID < HoArchive.wmlTypeID.InWorldIconWidget){
                            return new StaticGeometry(file);
                        }
                        return new InWorldIconWidget(file);
                    }
                    if (wmlTypeID < HoArchive.wmlTypeID.NPCGenericPool){
                        if (wmlTypeID < HoArchive.wmlTypeID.UI_Image){
                            if (wmlTypeID < HoArchive.wmlTypeID.UI_Motion){
                                return new ProjectileAsset(file);
                            }
                            return new UI_Motion(file);
                        }
                        if (wmlTypeID < HoArchive.wmlTypeID.LightKitScene){
                            return new UI_Image(file);
                        }
                        return new LightKitScene(file);
                    }
                    if (wmlTypeID < HoArchive.wmlTypeID.FMVReference){
                        if (wmlTypeID < HoArchive.wmlTypeID.TriggerPhantom){
                            return new NPCGenericPool(file);
                        }
                        return new TriggerPhantom(file);
                    }
                    if (wmlTypeID < HoArchive.wmlTypeID.PlantTrap){
                        return new FMVReference(file);
                    }
                    return new PlantTrap(file);
                }
                if (wmlTypeID < HoArchive.wmlTypeID.TriggerOG){
                    if (wmlTypeID < HoArchive.wmlTypeID.SkeletonBlob){
                        if (wmlTypeID < HoArchive.wmlTypeID.ComboAnimBlob){
                            if (wmlTypeID < HoArchive.wmlTypeID.Ribbon){
                                return new FXSpawn(file);
                            }
                            return new Ribbon(file);
                        }
                        if (wmlTypeID < HoArchive.wmlTypeID.Platform){
                            return new ComboAnimBlob(file);
                        }
                        return new Platform(file);
                    }
                    if (wmlTypeID < HoArchive.wmlTypeID.Curve){
                        if (wmlTypeID < HoArchive.wmlTypeID.Effect){
                            return new SkeletonBlob(file);
                        }
                        return new Effect(file);
                    }
                    if (wmlTypeID < HoArchive.wmlTypeID.PlayerAnimSeq){
                        return new Curve(file);
                    }
                    return new PlayerAnimSeq(file);
                }
                if (wmlTypeID < HoArchive.wmlTypeID.LightKit){
                    if (wmlTypeID < HoArchive.wmlTypeID.SimpleObject){
                        if (wmlTypeID < HoArchive.wmlTypeID.Destructible){
                            return new TriggerOG(file);
                        }
                        return new Destructible(file);
                    }
                    if (wmlTypeID < HoArchive.wmlTypeID.Decal){
                        return new SimpleObject(file);
                    }
                    return new Decal(file);
                }
                if (wmlTypeID < HoArchive.wmlTypeID.CollectibleSpawner){
                    if (wmlTypeID < HoArchive.wmlTypeID.GradientCurve){
                        return new LightKit(file);
                    }
                    return new GradientCurve(file);
                }
                if (wmlTypeID < HoArchive.wmlTypeID.Scene){
                    return new CollectibleSpawner(file);
                }
                return new Scene(file);
            }
            if (wmlTypeID < HoArchive.wmlTypeID.BehaviorSet){
                if (wmlTypeID < HoArchive.wmlTypeID.AnimBlendNode){
                    if (wmlTypeID < HoArchive.wmlTypeID.FloatingCollectible){
                        if (wmlTypeID < HoArchive.wmlTypeID.Conditional){
                            if (wmlTypeID < HoArchive.wmlTypeID.Binary_POI){
                                return new CollisionMesh(file);
                            }
                            return new Binary_POI(file);
                        }
                        if (wmlTypeID < HoArchive.wmlTypeID.RawBlob){
                            return new Conditional(file);
                        }
                        return new RawBlob(file);
                    }
                    if (wmlTypeID < HoArchive.wmlTypeID.UI_Controller){
                        if (wmlTypeID < HoArchive.wmlTypeID.StringsAsset){
                            return new FloatingCollectible(file);
                        }
                        return new StringsAsset(file);
                    }
                    if (wmlTypeID < HoArchive.wmlTypeID.Counter){
                        return new UI_Controller(file);
                    }
                    return new Counter(file);
                }
                if (wmlTypeID < HoArchive.wmlTypeID.Light_Effect_Strobe){
                    if (wmlTypeID < HoArchive.wmlTypeID.SoundBankWrap){
                        if (wmlTypeID < HoArchive.wmlTypeID.FontAsset){
                            return new AnimBlendNode(file);
                        }
                        return new FontAsset(file);
                    }
                    if (wmlTypeID < HoArchive.wmlTypeID.Timer){
                        return new SoundBankWrap(file);
                    }
                    return new Timer(file);
                }
                if (wmlTypeID < HoArchive.wmlTypeID.ImmediateModel){
                    if (wmlTypeID < HoArchive.wmlTypeID.WaterWheel){
                        return new Light_Effect_Strobe(file);
                    }
                    return new WaterWheel(file);
                }
                if (wmlTypeID < HoArchive.wmlTypeID.Player){
                    return new ImmediateModel(file);
                }
                return new Player(file);
            }
            if (wmlTypeID < HoArchive.wmlTypeID.PuckReflector){
                if (wmlTypeID < HoArchive.wmlTypeID.NPCGeneric){
                    if (wmlTypeID < HoArchive.wmlTypeID.Group){
                        if (wmlTypeID < HoArchive.wmlTypeID.NPC_Perception){
                            return new BehaviorSet(file);
                        }
                        return new NPC_Perception(file);
                    }
                    if (wmlTypeID < HoArchive.wmlTypeID.PolygonalVolume){
                        return new Group(file);
                    }
                    return new PolygonalVolume(file);
                }
                if (wmlTypeID < HoArchive.wmlTypeID.GlobalFX){
                    if (wmlTypeID < HoArchive.wmlTypeID.WallNetGroup){
                        return new NPCGeneric(file);
                    }
                    return new WallNetGroup(file);
                }
                if (wmlTypeID < HoArchive.wmlTypeID.Subtitles){
                    return new GlobalFX(file);
                }
                return new Subtitles(file);
            }
            if (wmlTypeID < HoArchive.wmlTypeID.FXInstance){
                if (wmlTypeID < HoArchive.wmlTypeID.UIDModelReference){
                    if (wmlTypeID < HoArchive.wmlTypeID.NPC_Combat){
                        return new PuckReflector(file);
                    }
                    return new NPC_Combat(file);
                }
                if (wmlTypeID < HoArchive.wmlTypeID.HudSB){
                    return new UIDModelReference(file);
                }
                return new HudSB(file);
            }
            if (wmlTypeID < HoArchive.wmlTypeID.TemplateInst){
                if (wmlTypeID < HoArchive.wmlTypeID.BungeeBall){
                    return new FXInstance(file);
                }
                return new BungeeBall(file);
            }
            if (wmlTypeID < HoArchive.wmlTypeID.RubberBand){
                return new TemplateInst(file);
            }
            return new RubberBand(file);
        }
    }
}